AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create bingo state machine and functions for each step

Parameters:
    TwitterConsumerKey: 
      Description: Twitter app consumer key
      Type: String
      NoEcho: true
      Default: ''

    TwitterConsumerSecret: 
      Description: Twitter app consumer secret
      Type: String
      NoEcho: true
      Default: ''

    TwitterAppSecret: 
      Description: Twitter app secret
      Type: String
      NoEcho: true
      Default: ''

    TwitterAppToken: 
      Description: Twitter app token
      Type: String 
      NoEcho: true
      Default: ''
Resources:

  BingoStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/bingo.json
      DefinitionSubstitutions:
        BingoMainFunctionArn: !GetAtt BingoMainFunction.Arn
        PostBingoBannerFunctionArn: !GetAtt PostBingoBannerFunction.Arn
        FindPlayersFunctionArn: !GetAtt FindPlayersFunction.Arn
        CreateTicketFunctionArn: !GetAtt CreateTicketFunction.Arn
        NumbersDrawFunctionArn: !GetAtt NumbersDrawFunction.Arn
        FindWinnerFunctionArn: !GetAtt FindWinnerFunction.Arn
        NotifyWinnerFunctionArn: !GetAtt NotifyWinnerFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref PostBingoBannerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FindPlayersFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateTicketFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NumbersDrawFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FindWinnerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyWinnerFunction

  BingoMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/main/index.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      # Layers:
      #   - arn:aws:lambda:sa-east-1:134621539640:layer:structured-log:1
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  PostBingoBannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/BingoBanner/app.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  FindPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/FindPlayers/app.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  CreateTicketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/CreateTicket/app.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  NumbersDrawFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/NumbersDraw/app.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  FindWinnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/FindWinner/app.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  NotifyWinnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/NotifyWinner/app.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken

  BingoTicketTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: TicketHash
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: TicketHash
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
      TableName: BingoTicket
      Tags:
        - Key: Project
          Value: sam-bingo-app

  BingoRaffleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: raffle
          AttributeType: "S"
        - 
          AttributeName: date
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: raffle
          KeyType: "HASH"
        - 
          AttributeName: date
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
      TableName: BingoRaffle
      Tags:
        - Key: Project
          Value: sam-bingo-app

  CreateTicketTableConnection:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: CreateTicketFunction
      Destination:
        Id: BingoTicketTable
      Permissions:
        - Write
        - Read

  NumbersDrawTableConnection:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: NumbersDrawFunction
      Destination:
        Id: BingoRaffleTable
      Permissions:
        - Write
        - Read

  FindWinnerTableConnection:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: FindWinnerFunction
      Destination:
        Id: BingoTicketTable
      Permissions:
        - Read