AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Create simple lambda function.

Parameters:
    TwitterConsumerKey: 
      Description: Twitter app consumer key
      Type: String
      NoEcho: true
      Default: ''

    TwitterConsumerSecret: 
      Description: Twitter app consumer secret
      Type: String
      NoEcho: true
      Default: ''

    TwitterAppSecret: 
      Description: Twitter app secret
      Type: String
      NoEcho: true
      Default: ''

    TwitterAppToken: 
      Description: Twitter app token
      Type: String 
      NoEcho: true
      Default: ''
Resources:

  BingoStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/bingo.json
      DefinitionSubstitutions:
        BingoMainFunctionArn: !GetAtt BingoMainFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref BingoMainFunction

  BingoMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/functions/main/index.handler
      Runtime: nodejs14.x
      PackageType: Zip
      Timeout: 120
      MemorySize: 128
      # Layers:
      #   - arn:aws:lambda:sa-east-1:134621539640:layer:structured-log:1
      Environment:
        Variables:
          CONSUMER_KEY: !Ref TwitterConsumerKey
          CONSUMER_SECRET: !Ref TwitterConsumerSecret
          SECRET: !Ref TwitterAppSecret
          TOKEN: !Ref TwitterAppToken
    Metadata:
      SamResourceId: bingoLambda

  BingoTicketTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: TicketHash
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: TicketHash
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
      TableName: BingoTicket
      Tags:
        - Key: Project
          Value: sam-bingo-app

  BingoRaffleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: raffle
          AttributeType: "S"
        - 
          AttributeName: date
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: raffle
          KeyType: "HASH"
        - 
          AttributeName: date
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
      TableName: BingoRaffle
      Tags:
        - Key: Project
          Value: sam-bingo-app

  MainFunctionRaffleTableConnection:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: BingoMainFunction
      Destination:
        Id: BingoRaffleTable
      Permissions:
        - Write

  MainFunctionTicketTableConnection:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: BingoMainFunction
      Destination:
        Id: BingoTicketTable
      Permissions:
        - Write